// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rbind_fill_worker
List rbind_fill_worker(List dfs, IntegerVector rows, int nrows);
RcppExport SEXP plyr_rbind_fill_worker(SEXP dfsSEXP, SEXP rowsSEXP, SEXP nrowsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    List dfs = Rcpp::as<List >(dfsSEXP);
    IntegerVector rows = Rcpp::as<IntegerVector >(rowsSEXP);
    int nrows = Rcpp::as<int >(nrowsSEXP);
    List __result = rbind_fill_worker(dfs, rows, nrows);
    return Rcpp::wrap(__result);
END_RCPP
}
