# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rbind.fill.worker.rcpp <- function(dfs, rows, nrows) {
    .Call('plyr_rbind_fill_worker', PACKAGE = 'plyr', dfs, rows, nrows)
}

